# https://www.gitpod.io/guides/gitpodify#postgresql

image: 
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - cweijan.vscode-mysql-client2
    - vscjava.vscode-java-pack
tasks:
    - init: create postgres user
      command: psql -c 'create user postgres'
